export const reviews = [
  {
    id: 1,
    toolName: "ChatGPT",
    rating: 4.8,
    category: "Text Generation",
    content: "ChatGPT has completely transformed how I handle content creation and research. The responses are incredibly detailed and contextually aware. While it occasionally needs fact-checking, it's an invaluable tool for brainstorming and getting quick, comprehensive answers.",
    likes: 245,
    comments: 42,
    date: "Mar 14, 2024",
    reviewer: {
      name: "David Wilson",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100"
    }
  },
  {
    id: 2,
    toolName: "Midjourney",
    rating: 4.7,
    category: "Image Generation",
    content: "The quality of images generated by Midjourney is absolutely stunning. It's incredible how it can transform text descriptions into beautiful artwork. The learning curve is a bit steep, but once you understand the prompting system, the possibilities are endless.",
    likes: 189,
    comments: 35,
    date: "Mar 13, 2024",
    reviewer: {
      name: "Emily Parker",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=100"
    }
  },
  {
    id: 3,
    toolName: "GitHub Copilot",
    rating: 4.6,
    category: "Code Assistance",
    content: "As a developer, GitHub Copilot has significantly improved my coding speed. It's like having a pair programmer who understands your coding style. The suggestions are usually spot-on, and it's particularly helpful with boilerplate code and common patterns.",
    likes: 156,
    comments: 28,
    date: "Mar 12, 2024",
    reviewer: {
      name: "Ryan Zhang",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100"
    }
  }
];